CREATE DATABASE Optus;

USE Optus;

CREATE TABLE Artista
(
	idArtista INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL
);

CREATE TABLE Album
(
	idAlbum INT PRIMARY KEY IDENTITY
	,idArtista INT FOREIGN KEY REFERENCES Artista(idArtista)
	,Titulo VARCHAR(200) NOT NULL
	,DataLancamento DATE NOT NULL
	,QntdMinutos INT NOT NULL
	,Ativo BIT NOT NULL
);

ALTER TABLE Album
DROP COLUMN DataLancamento;

ALTER TABLE Album
ADD DataLancamento DATE;

CREATE TABLE Estilo
(
	idEstilo INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL
);

CREATE TABLE AlbumEstilo
(
	idAlbum INT FOREIGN KEY REFERENCES Album(idAlbum)
	,idEstilo INT FOREIGN KEY REFERENCES Estilo(idEstilo)
);

CREATE TABLE Usuario
(
	idUsuario INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL
	,Email VARCHAR(200) NOT NULL
	,Senha VARCHAR(200) NOT NULL
	,Permissao BIT NOT NULL
);